/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Dashboard;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.smartcardio.Card;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import libs.DBConnect;
import Moduls.Book.*;

/**
 *
 * @author ThinkPad
 */
public class MainDashboard extends javax.swing.JFrame {
    
    
    public MainDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        navigasi_buku = new javax.swing.JButton();
        navigasi_anggota = new javax.swing.JButton();
        navigasi_kunjungan = new javax.swing.JButton();
        navigasi_peminjaman = new javax.swing.JButton();
        navigasi_pengembalian = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        Buku = new javax.swing.JPanel();
        JUDUL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Anggota = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Kunjungan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Peminjaman = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Pengembalian = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Pengaturan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 455));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERPUSTAKAAN");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 200, 48));

        navigasi_buku.setText("BUKU");
        navigasi_buku.setBorderPainted(false);
        navigasi_buku.setContentAreaFilled(false);
        navigasi_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigasi_bukuActionPerformed(evt);
            }
        });
        jPanel1.add(navigasi_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 35));

        navigasi_anggota.setText("ANGGOTA");
        navigasi_anggota.setBorderPainted(false);
        navigasi_anggota.setContentAreaFilled(false);
        navigasi_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigasi_anggotaActionPerformed(evt);
            }
        });
        jPanel1.add(navigasi_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 35));

        navigasi_kunjungan.setText("KUNJUNGAN");
        navigasi_kunjungan.setBorderPainted(false);
        navigasi_kunjungan.setContentAreaFilled(false);
        navigasi_kunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigasi_kunjunganActionPerformed(evt);
            }
        });
        jPanel1.add(navigasi_kunjungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 35));

        navigasi_peminjaman.setText("PEMINJAMAN");
        navigasi_peminjaman.setBorderPainted(false);
        navigasi_peminjaman.setContentAreaFilled(false);
        navigasi_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigasi_peminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(navigasi_peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 35));

        navigasi_pengembalian.setText("PENGEMBALIAN");
        navigasi_pengembalian.setBorderPainted(false);
        navigasi_pengembalian.setContentAreaFilled(false);
        navigasi_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigasi_pengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(navigasi_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 35));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, -1));

        mainPanel.setPreferredSize(new java.awt.Dimension(400, 455));
        mainPanel.setLayout(new java.awt.CardLayout());

        JUDUL.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        JUDUL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUDUL.setText("BUKU");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CATEGORY");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("LAPORAN");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("BUKU");

        javax.swing.GroupLayout BukuLayout = new javax.swing.GroupLayout(Buku);
        Buku.setLayout(BukuLayout);
        BukuLayout.setHorizontalGroup(
            BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JUDUL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(BukuLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BukuLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BukuLayout.setVerticalGroup(
            BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BukuLayout.createSequentialGroup()
                .addComponent(JUDUL)
                .addGap(36, 36, 36)
                .addGroup(BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        mainPanel.add(Buku, "buku");

        Anggota.setPreferredSize(new java.awt.Dimension(400, 455));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ANGGOTA");

        javax.swing.GroupLayout AnggotaLayout = new javax.swing.GroupLayout(Anggota);
        Anggota.setLayout(AnggotaLayout);
        AnggotaLayout.setHorizontalGroup(
            AnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        AnggotaLayout.setVerticalGroup(
            AnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnggotaLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 241, Short.MAX_VALUE))
        );

        mainPanel.add(Anggota, "anggota");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("KUNJUNGAN");

        javax.swing.GroupLayout KunjunganLayout = new javax.swing.GroupLayout(Kunjungan);
        Kunjungan.setLayout(KunjunganLayout);
        KunjunganLayout.setHorizontalGroup(
            KunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        KunjunganLayout.setVerticalGroup(
            KunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KunjunganLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 241, Short.MAX_VALUE))
        );

        mainPanel.add(Kunjungan, "kunjungan");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PEMINJAMAN");

        javax.swing.GroupLayout PeminjamanLayout = new javax.swing.GroupLayout(Peminjaman);
        Peminjaman.setLayout(PeminjamanLayout);
        PeminjamanLayout.setHorizontalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PeminjamanLayout.setVerticalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeminjamanLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 241, Short.MAX_VALUE))
        );

        mainPanel.add(Peminjaman, "peminjaman");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PENGEMBALIAN");

        javax.swing.GroupLayout PengembalianLayout = new javax.swing.GroupLayout(Pengembalian);
        Pengembalian.setLayout(PengembalianLayout);
        PengembalianLayout.setHorizontalGroup(
            PengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PengembalianLayout.setVerticalGroup(
            PengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengembalianLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 241, Short.MAX_VALUE))
        );

        mainPanel.add(Pengembalian, "pengembalian");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PENGATURAN");

        javax.swing.GroupLayout PengaturanLayout = new javax.swing.GroupLayout(Pengaturan);
        Pengaturan.setLayout(PengaturanLayout);
        PengaturanLayout.setHorizontalGroup(
            PengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        PengaturanLayout.setVerticalGroup(
            PengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengaturanLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 241, Short.MAX_VALUE))
        );

        mainPanel.add(Pengaturan, "pengaturan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void navigasi_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigasi_anggotaActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "anggota");
    }//GEN-LAST:event_navigasi_anggotaActionPerformed

    private void navigasi_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigasi_bukuActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "buku");
    }//GEN-LAST:event_navigasi_bukuActionPerformed

    private void navigasi_kunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigasi_kunjunganActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "kunjungan");
    }//GEN-LAST:event_navigasi_kunjunganActionPerformed

    private void navigasi_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigasi_peminjamanActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "peminjaman");
    }//GEN-LAST:event_navigasi_peminjamanActionPerformed

    private void navigasi_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigasi_pengembalianActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "pengembalian");
    }//GEN-LAST:event_navigasi_pengembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Anggota;
    private javax.swing.JPanel Buku;
    private javax.swing.JLabel JUDUL;
    private javax.swing.JPanel Kunjungan;
    private javax.swing.JPanel Peminjaman;
    private javax.swing.JPanel Pengaturan;
    private javax.swing.JPanel Pengembalian;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton navigasi_anggota;
    private javax.swing.JButton navigasi_buku;
    private javax.swing.JButton navigasi_kunjungan;
    private javax.swing.JButton navigasi_peminjaman;
    private javax.swing.JButton navigasi_pengembalian;
    // End of variables declaration//GEN-END:variables
}
