/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Dashboard;

import View.Anggota.Anggota;
import View.Book.Book;
import View.Book.Category;
import View.Kunjungan.Kunjungan;
import View.Transaksi.Peminjaman.Peminjaman;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import libs.PrintReport;

/**
 *
 * @author ThinkPad
 */
public class Main extends javax.swing.JFrame {

    Color ACTIVE_COLOR = new Color(44,62,80); 
    Color DEACTIVE_COLOR = new Color(52,73,94); 
    int SELECTED_LIST = 0;
    
    /** Creates new form Main */
    public Main() {
        initComponents();
    }
    
    public void resetBG () {
        if(SELECTED_LIST ==0) {
            list_kunjungan.setBackground(DEACTIVE_COLOR);    
            list_peminjaman.setBackground(DEACTIVE_COLOR);    
            list_anggota.setBackground(DEACTIVE_COLOR);
            list_tentang.setBackground(DEACTIVE_COLOR);            
        } else if(SELECTED_LIST ==1) {
            list_buku.setBackground(DEACTIVE_COLOR);   
            list_peminjaman.setBackground(DEACTIVE_COLOR);    
            list_anggota.setBackground(DEACTIVE_COLOR);
            list_tentang.setBackground(DEACTIVE_COLOR);            
        } else if(SELECTED_LIST ==2) {
            list_buku.setBackground(DEACTIVE_COLOR);
            list_kunjungan.setBackground(DEACTIVE_COLOR);    
            list_anggota.setBackground(DEACTIVE_COLOR);
            list_tentang.setBackground(DEACTIVE_COLOR);            
        } else if(SELECTED_LIST ==3) {
            list_buku.setBackground(DEACTIVE_COLOR);
            list_kunjungan.setBackground(DEACTIVE_COLOR);    
            list_peminjaman.setBackground(DEACTIVE_COLOR);
            list_tentang.setBackground(DEACTIVE_COLOR);            
        } else if(SELECTED_LIST ==4) {            
            list_buku.setBackground(DEACTIVE_COLOR);
            list_kunjungan.setBackground(DEACTIVE_COLOR);    
            list_anggota.setBackground(DEACTIVE_COLOR);
            list_peminjaman.setBackground(DEACTIVE_COLOR);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainList = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        list_kunjungan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        list_buku = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        list_anggota = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        list_peminjaman = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        list_tentang = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        breadcum = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        Buku = new javax.swing.JPanel();
        button_kategori = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button_buku = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        button_print_buku = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Kunjungan = new javax.swing.JPanel();
        button_kunjungan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        button_print_kunjungan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Anggota = new javax.swing.JPanel();
        button_anggota = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Peminjaman = new javax.swing.JPanel();
        button_peminjaman = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TentangKami = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainList.setBackground(new java.awt.Color(52, 73, 94));
        MainList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Perpustakaan Ibnu Khaldun");
        MainList.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 38));

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        MainList.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 207, -1));

        list_kunjungan.setBackground(new java.awt.Color(52, 73, 94));
        list_kunjungan.setPreferredSize(new java.awt.Dimension(169, 43));
        list_kunjungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_kunjunganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_kunjunganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                list_kunjunganMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kunjungan");

        javax.swing.GroupLayout list_kunjunganLayout = new javax.swing.GroupLayout(list_kunjungan);
        list_kunjungan.setLayout(list_kunjunganLayout);
        list_kunjunganLayout.setHorizontalGroup(
            list_kunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_kunjunganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        list_kunjunganLayout.setVerticalGroup(
            list_kunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_kunjunganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainList.add(list_kunjungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 227, 40));

        list_buku.setBackground(new java.awt.Color(44, 62, 80));
        list_buku.setPreferredSize(new java.awt.Dimension(227, 43));
        list_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_bukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                list_bukuMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buku");

        javax.swing.GroupLayout list_bukuLayout = new javax.swing.GroupLayout(list_buku);
        list_buku.setLayout(list_bukuLayout);
        list_bukuLayout.setHorizontalGroup(
            list_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_bukuLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        list_bukuLayout.setVerticalGroup(
            list_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_bukuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainList.add(list_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        list_anggota.setBackground(new java.awt.Color(52, 73, 94));
        list_anggota.setPreferredSize(new java.awt.Dimension(227, 43));
        list_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_anggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_anggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                list_anggotaMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Anggota");

        javax.swing.GroupLayout list_anggotaLayout = new javax.swing.GroupLayout(list_anggota);
        list_anggota.setLayout(list_anggotaLayout);
        list_anggotaLayout.setHorizontalGroup(
            list_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_anggotaLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        list_anggotaLayout.setVerticalGroup(
            list_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_anggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainList.add(list_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 209, -1, -1));

        list_peminjaman.setBackground(new java.awt.Color(52, 73, 94));
        list_peminjaman.setPreferredSize(new java.awt.Dimension(227, 43));
        list_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_peminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_peminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                list_peminjamanMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peminjaman");

        javax.swing.GroupLayout list_peminjamanLayout = new javax.swing.GroupLayout(list_peminjaman);
        list_peminjaman.setLayout(list_peminjamanLayout);
        list_peminjamanLayout.setHorizontalGroup(
            list_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_peminjamanLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        list_peminjamanLayout.setVerticalGroup(
            list_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_peminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainList.add(list_peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, -1, -1));

        list_tentang.setBackground(new java.awt.Color(52, 73, 94));
        list_tentang.setPreferredSize(new java.awt.Dimension(227, 43));
        list_tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_tentangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_tentangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                list_tentangMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Tentang Kami");

        javax.swing.GroupLayout list_tentangLayout = new javax.swing.GroupLayout(list_tentang);
        list_tentang.setLayout(list_tentangLayout);
        list_tentangLayout.setHorizontalGroup(
            list_tentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_tentangLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        list_tentangLayout.setVerticalGroup(
            list_tentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_tentangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainList.add(list_tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        getContentPane().add(MainList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        jPanel3.setBackground(new java.awt.Color(240, 234, 223));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        breadcum.setFont(new java.awt.Font("DokChampa", 0, 16)); // NOI18N
        breadcum.setText("Dashboard > Buku");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(breadcum)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(breadcum)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 0, 500, -1));

        MainPanel.setLayout(new java.awt.CardLayout());

        button_kategori.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        button_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_kategoriMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Data Kategori");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/big-pushpin.png"))); // NOI18N

        javax.swing.GroupLayout button_kategoriLayout = new javax.swing.GroupLayout(button_kategori);
        button_kategori.setLayout(button_kategoriLayout);
        button_kategoriLayout.setHorizontalGroup(
            button_kategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(button_kategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3))
        );
        button_kategoriLayout.setVerticalGroup(
            button_kategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_kategoriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        button_buku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        button_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_bukuMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Data Buku");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/blank-archive.png"))); // NOI18N

        javax.swing.GroupLayout button_bukuLayout = new javax.swing.GroupLayout(button_buku);
        button_buku.setLayout(button_bukuLayout);
        button_bukuLayout.setHorizontalGroup(
            button_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_bukuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(button_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_bukuLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap())))
        );
        button_bukuLayout.setVerticalGroup(
            button_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_bukuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addGap(37, 37, 37)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        button_print_buku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        button_print_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_print_bukuMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home-printer.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Print Buku");

        javax.swing.GroupLayout button_print_bukuLayout = new javax.swing.GroupLayout(button_print_buku);
        button_print_buku.setLayout(button_print_bukuLayout);
        button_print_bukuLayout.setHorizontalGroup(
            button_print_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_print_bukuLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_print_bukuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        button_print_bukuLayout.setVerticalGroup(
            button_print_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_print_bukuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addGap(29, 29, 29)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BukuLayout = new javax.swing.GroupLayout(Buku);
        Buku.setLayout(BukuLayout);
        BukuLayout.setHorizontalGroup(
            BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BukuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_print_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BukuLayout.setVerticalGroup(
            BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BukuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_kategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_buku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_print_buku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        MainPanel.add(Buku, "BukuCard");

        button_kunjungan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        button_kunjungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_kunjunganMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/paste-document.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Data Kunjungan");

        javax.swing.GroupLayout button_kunjunganLayout = new javax.swing.GroupLayout(button_kunjungan);
        button_kunjungan.setLayout(button_kunjunganLayout);
        button_kunjunganLayout.setHorizontalGroup(
            button_kunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_kunjunganLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_kunjunganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        button_kunjunganLayout.setVerticalGroup(
            button_kunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_kunjunganLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        button_print_kunjungan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        button_print_kunjungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_print_kunjunganMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home-printer.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Print Kunjungan");

        javax.swing.GroupLayout button_print_kunjunganLayout = new javax.swing.GroupLayout(button_print_kunjungan);
        button_print_kunjungan.setLayout(button_print_kunjunganLayout);
        button_print_kunjunganLayout.setHorizontalGroup(
            button_print_kunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_print_kunjunganLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_print_kunjunganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        button_print_kunjunganLayout.setVerticalGroup(
            button_print_kunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_print_kunjunganLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addGap(29, 29, 29)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout KunjunganLayout = new javax.swing.GroupLayout(Kunjungan);
        Kunjungan.setLayout(KunjunganLayout);
        KunjunganLayout.setHorizontalGroup(
            KunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KunjunganLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(button_kunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(button_print_kunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        KunjunganLayout.setVerticalGroup(
            KunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KunjunganLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(KunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_print_kunjungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_kunjungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        MainPanel.add(Kunjungan, "KunjunganCard");

        button_anggota.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        button_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_anggotaMouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/new-credit-card.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Data Anggota");

        javax.swing.GroupLayout button_anggotaLayout = new javax.swing.GroupLayout(button_anggota);
        button_anggota.setLayout(button_anggotaLayout);
        button_anggotaLayout.setHorizontalGroup(
            button_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_anggotaLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_anggotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );
        button_anggotaLayout.setVerticalGroup(
            button_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_anggotaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addGap(29, 29, 29)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AnggotaLayout = new javax.swing.GroupLayout(Anggota);
        Anggota.setLayout(AnggotaLayout);
        AnggotaLayout.setHorizontalGroup(
            AnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnggotaLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(button_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        AnggotaLayout.setVerticalGroup(
            AnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnggotaLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(button_anggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(93, 93, 93))
        );

        MainPanel.add(Anggota, "AnggotaCard");

        button_peminjaman.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        button_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_peminjamanMouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/to-do-list.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Data Peminjaman");

        javax.swing.GroupLayout button_peminjamanLayout = new javax.swing.GroupLayout(button_peminjaman);
        button_peminjaman.setLayout(button_peminjamanLayout);
        button_peminjamanLayout.setHorizontalGroup(
            button_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_peminjamanLayout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_peminjamanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addContainerGap())
        );
        button_peminjamanLayout.setVerticalGroup(
            button_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_peminjamanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel23)
                .addGap(29, 29, 29)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PeminjamanLayout = new javax.swing.GroupLayout(Peminjaman);
        Peminjaman.setLayout(PeminjamanLayout);
        PeminjamanLayout.setHorizontalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeminjamanLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(button_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        PeminjamanLayout.setVerticalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeminjamanLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(button_peminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(83, 83, 83))
        );

        MainPanel.add(Peminjaman, "PeminjamanCard");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Tentang Kami :");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/whatsapp.png"))); // NOI18N
        jLabel25.setText("083822457942");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/instagram.png"))); // NOI18N
        jLabel26.setText("@timjuara");

        jTextPane1.setText("Kami adalah Mahasiswa Sekolah Tinggi Teknologi Bandung \nProgram Studi Informatika Angkatan 2017.\n\nProduct Version: Perpustakaan 1.0 (Build 20170707)\nUpdates: -\nJava: 1.8.0_171; Java HotSpot(TM) 64-Bit Server VM 25.171-b11\nRuntime: Java(TM) SE Runtime Environment 1.8.0_171-b11\nSystem: Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)))
                        .addGap(0, 271, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addContainerGap())
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/sttb.PNG"))); // NOI18N

        javax.swing.GroupLayout TentangKamiLayout = new javax.swing.GroupLayout(TentangKami);
        TentangKami.setLayout(TentangKamiLayout);
        TentangKamiLayout.setHorizontalGroup(
            TentangKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TentangKamiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(TentangKamiLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TentangKamiLayout.setVerticalGroup(
            TentangKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TentangKamiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        MainPanel.add(TentangKami, "TentangCard");

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 500, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void list_bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_bukuMouseEntered
        // TODO add your handling code here:
        resetBG();
        list_buku.setBackground(ACTIVE_COLOR);
    }//GEN-LAST:event_list_bukuMouseEntered

    private void list_bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_bukuMouseExited
        // TODO add your handling code here:
        resetBG();
    }//GEN-LAST:event_list_bukuMouseExited

    private void list_kunjunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_kunjunganMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "KunjunganCard");
        SELECTED_LIST = 1;
        breadcum.setText("Dashboard > Kunjungan");
        resetBG();
    }//GEN-LAST:event_list_kunjunganMouseClicked

    private void list_kunjunganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_kunjunganMouseEntered
        // TODO add your handling code here:
        resetBG();
        list_kunjungan.setBackground(ACTIVE_COLOR);  
    }//GEN-LAST:event_list_kunjunganMouseEntered

    private void list_kunjunganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_kunjunganMouseExited
        // TODO add your handling code here:
        resetBG();
    }//GEN-LAST:event_list_kunjunganMouseExited

    private void list_peminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_peminjamanMouseEntered
        // TODO add your handling code here:
        resetBG();
        list_peminjaman.setBackground(ACTIVE_COLOR);      
    }//GEN-LAST:event_list_peminjamanMouseEntered

    private void list_peminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_peminjamanMouseExited
        // TODO add your handling code here:
        resetBG();
    }//GEN-LAST:event_list_peminjamanMouseExited

    private void list_anggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_anggotaMouseEntered
        // TODO add your handling code here:
        resetBG();
        list_anggota.setBackground(ACTIVE_COLOR);
    }//GEN-LAST:event_list_anggotaMouseEntered

    private void list_anggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_anggotaMouseExited
        // TODO add your handling code here:
        resetBG();
    }//GEN-LAST:event_list_anggotaMouseExited

    private void list_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_bukuMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "BukuCard");
        SELECTED_LIST = 0;
        breadcum.setText("Dashboard > Buku");
        resetBG();
    }//GEN-LAST:event_list_bukuMouseClicked

    private void list_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_peminjamanMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "PeminjamanCard");
        SELECTED_LIST = 2;
        breadcum.setText("Dashboard > Peminjaman");
        resetBG();
    }//GEN-LAST:event_list_peminjamanMouseClicked

    private void list_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_anggotaMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "AnggotaCard");
        SELECTED_LIST = 3;
        breadcum.setText("Dashboard > Anggota");
        resetBG();
    }//GEN-LAST:event_list_anggotaMouseClicked

    private void button_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_bukuMouseClicked
        // TODO add your handling code here:
        Book book = new Book();
        book.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_bukuMouseClicked

    private void button_kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_kategoriMouseClicked
        // TODO add your handling code here:
        Category category = new Category();
        category.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_kategoriMouseClicked

    private void button_kunjunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_kunjunganMouseClicked
        // TODO add your handling code here:
        Kunjungan kunjungan = new Kunjungan();
        kunjungan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_kunjunganMouseClicked

    private void button_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_anggotaMouseClicked
        // TODO add your handling code here:
        Anggota anggota = new Anggota();
        anggota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_anggotaMouseClicked

    private void button_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_peminjamanMouseClicked
        // TODO add your handling code here:
        Peminjaman peminjaman = new Peminjaman();
        peminjaman.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_peminjamanMouseClicked

    private void list_tentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_tentangMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "TentangCard");
        SELECTED_LIST = 4;
        breadcum.setText("Dashboard > Tentang Kami");
        resetBG();
    }//GEN-LAST:event_list_tentangMouseClicked

    private void list_tentangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_tentangMouseEntered
        // TODO add your handling code here:
        resetBG();
        list_tentang.setBackground(ACTIVE_COLOR);
    }//GEN-LAST:event_list_tentangMouseEntered

    private void list_tentangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_tentangMouseExited
        // TODO add your handling code here:
        resetBG();
    }//GEN-LAST:event_list_tentangMouseExited

    private void button_print_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_print_bukuMouseClicked
        // TODO add your handling code here:
        new PrintReport("./src/Moduls/Book/ReportBook.jasper");
    }//GEN-LAST:event_button_print_bukuMouseClicked

    private void button_print_kunjunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_print_kunjunganMouseClicked
        // TODO add your handling code here:
        new PrintReport("./src/Moduls/Kunjungan/ReportKunjungan.jasper");
    }//GEN-LAST:event_button_print_kunjunganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Anggota;
    private javax.swing.JPanel Buku;
    private javax.swing.JPanel Kunjungan;
    private javax.swing.JPanel MainList;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Peminjaman;
    private javax.swing.JPanel TentangKami;
    private javax.swing.JLabel breadcum;
    private javax.swing.JPanel button_anggota;
    private javax.swing.JPanel button_buku;
    private javax.swing.JPanel button_kategori;
    private javax.swing.JPanel button_kunjungan;
    private javax.swing.JPanel button_peminjaman;
    private javax.swing.JPanel button_print_buku;
    private javax.swing.JPanel button_print_kunjungan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel list_anggota;
    private javax.swing.JPanel list_buku;
    private javax.swing.JPanel list_kunjungan;
    private javax.swing.JPanel list_peminjaman;
    private javax.swing.JPanel list_tentang;
    // End of variables declaration//GEN-END:variables

}
